### ISSUE TITLE
Docs? How do I use this to store binary files like one would do on Amazon S3

### ISSUE THREAD

**Issue by ebdrup** [outscale/osc-sdk-js#20]
I don't see any docs here. Could you guide me on how to use this to store images on OUTSCALE Object Storage (OOS)?

**Comment by jerome-jutteau** [comment]
Hi @ebdrup ,

This SDK is generated to interact with [Outscale API service](https://docs.outscale.com/api) (based on [openapi description](https://github.com/outscale/osc-api)) but not OOS service.
OOS is based on S3 API so you should be able to use a S3-compatible SDK.

We will make sure to clarify this projet documentation.
